deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: havakv
  password:
    secure: YtzZGlD039p9ZbL6WgqC7nSHM8iG9gehILTbuU165wbUaF4T5HoblaaY3WJWx//mthTM5OQKLPUsRklQRFh6SjV7dkqCkNqFmxiPgkwQ6wkq70SDXkeqSMne6psSrNH/Y31oqGedTb1agA82ek6XXf3TqicsGYoEH63BZUXTF4T4rCDq82raGUgI5o9I7sVTIkhhQDLqqMKOXHmOSe/7xVatNtHFyAUaY3/xO6IvSStqmFQHL1mGILraTXnjm1/2YPqao0yzgZrlKWJ27v1alNzQ/Eddx7a+k67kurj0LxfGRexl8nEBgAoztPrZap2DOb8PHp8hEDAz5GVVzAlAL2uf+hGehjCfppF47el8lFuWyMnhVYIMA1g/vqBOKhZkZTOqZnQtiDBa+fVVw9N5uauwzLyUmYDzeiUiAKJWf2eoClJYMVvVutl4czRnF5Q8oH99kCnnaTBpz2ppdCjZAMb4vXroOm4XqtihwNvoed6Ha6H943goWgBo6fNkh+YqTblC0oCDzHPPedakxFBxuEJ6d3LVs3bqVxRFppiU8YPTZZ3/zydVXDyeaCFrJMVSXoO/9ZQxEonhyWEtvxiKlKiLfKq/Rnj6W/mgYBRuljkho4Ap+jPu81krGc4XhfUNF7ES9430734LVqtjF2ctfUBQH1mMCbcOmZJz2B9mJxQ=
  on:
    python: 3.7
    repo: havakv/safescope
    tags: true
install:
- pip install -U pytest
- python setup.py install
language: python
python:
- 3.7
- 3.6
- 3.5
script: py.test
