deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: havakv
  password:
    secure: 4AHkOZUuCmXXANzll7UvZgHVuThnW8gZ1N4/KBKsabIAkXkx71Cj1hxL/5b7Qi0rbUgshdk9Yg1DuNtmi8AB7bA8du6fVXuIatnjyhQ5jZAOJCNk8axLWek40q3el0PF1xL4dNlwjqIdIClXsdirVSc26PmKjiHP+NYq5K6qElkqCVXCh6YAlrNctt6hz5cJxQYiqiUuksFAWJixVoyxFNLcPnu8D7nmjuaIW90PDRnMsWUqnc5SMrrF8BvCzIP25Vf+Ay1MqnULn/qeH34y161Evepe7znHF+Yisbmw6RHFxuDJ2KtYJ5I7WAiE9aH5nNRxcD89UUCoSmHppp9Dne8I1D1BJMxMxbEZYjwPGPVfQ8mcCr1hIZDokmuM1U8SIUsKIHeWmRCpkEgr/NUr8Pv1bbRnKwXKRpW06kzgwHv4mNexoAkvHPJhx2/gYKP9ER2i64irJad24egstn6cbO4v8nnfEdLTD2ssjEpw9f6QSagj+2t1WgKA/uKpgHh+POTtTVpoqbzBT3MMZ++aT14i+4Xp8plE/JjEUGzKsM0nsD98ombLG+XfBnUsQq3PNR8tPKX9LUo5+WYY8it33grLisuO+FjIHDn6GAss6Ry1wNmEe4sdy6iVRreVToYXHay96r4yNHdOG2xz732do4qWYAysEQX9EuXj0hIqugs=
  on:
    python: 3.7
    repo: havakv/safescope
    tags: true
install:
- pip install -U pytest
- python setup.py install
language: python
python:
- 3.7
- 3.6
- 3.5
script: py.test
