deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: havakv
  password:
    secure: yg1qGYPixfwqNfawkQkuakgonNRIhMrZJXxB3I5vuUUa0ml5qEUqjHKO67p4Z1hq324WFL7bpjuBXvyvJyMuvWeUWb13INrJo67iQPOCAGV0pvmowJ4716r28Xe9lDwx5NzzTYX6rvQ6tu0OcPb+5WbL3q7LKlobyL2hHsZZiqas6p9ux+WlH5nTc6y3s6LYTgs4Zyb2bxwXlPyUPb02cVWXkyEvDeh1VWVFbPPQA3qcoZ7bJX+hEfqr6Hj5KFhF4/nmW97I2UGGAfsSdXitK4oSsbQHbz+/mjg/o/SApctUnhaxQhB9KTwYfc+kVFlmGPqqmUlBGsdfbOF7YriPyT1eOeJ/5ANGDDORhjHo3rtQyvkEnqdIhr9Oqhbd7lvBkcqAtYgzHLNMxLprVBoW3F+mNbnZZIPFGyFRh8rjJVYrfM/1yVVrQZGdvyqWBRPCAsRQhiBqckvOxligLY0rGtXftsD2jGuUpFnuXjp7UKN0rca6gfOQmLF0N0sWQPGyHoHpeZ2t+n3WE7jj/HaceFSKufIKDOrfh4JmuVkmNwbRHk6+phpEuzaZ7pPcv0QehnnSxcZd5EXc5j/q8w3asktZicAf63r6yNq3ZphnGC/EiM97QTL6ttB+ddK2P4QcL8LGjHLHUkOlDrr+TlhPfiJQ8FBH+kYQidGmI6cnAxc=
  skip_existing: true
  on:
    python: 3.7
    repo: havakv/safescope
    tags: true
install:
- pip install -U pytest
- python setup.py install
language: python
python:
- 3.7
- 3.6
- 3.5
script: py.test
